[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions  = [{ access = "read", path = "./"}]     # Gives permission to read files for compilation objects.

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${RPC_URL}"

[privatekey]
privatekey = "${PRIVATE_KEY}"